## Travis CI configuration for the cookiecutter-python-lib project template.
##
##   <https://travis-ci.org/mdklatt/cookiecutter-python-lib>
##
language: python

python:
  - "2.7"

branches:
  only:
    - master
    - dev

sudo: false

before_script:
  - pip install -r requirements.txt -r tests/requirements.txt

script:
  - python tests/test_template.py
