## Travis CI configuration for the cookiecutter-python-lib project template.
##
language: python
python:
  - "2.7"

branches:
  only:
    - master
    - dev

sudo: false

before_script:
  - pip install --requirement=requirements.txt

script:
  - bash test.bash
