## Travis CI configuration for the cookiecutter-python-lib project template.
##
##   <https://travis-ci.org/mdklatt/cookiecutter-python-lib>
##
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

branches:
  only:
    # TODO: master 
    # TODO: dev
    - py34

sudo: false

install:
  - pip install --requirement=requirements.txt --requirement=tests/requirements.txt

script:
  - python tests/test_template.py
